"""Add new table

Revision ID: e66ed0c15f45
Revises: 5d5afa2774d4
Create Date: 2024-12-30 15:53:47.564084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66ed0c15f45'
down_revision: Union[str, None] = '5d5afa2774d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saunas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('prefecture', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Text(), nullable=False),
    sa.Column('longitude', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favorites', sa.Column('sauna_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorites', 'saunas', ['sauna_id'], ['id'])
    op.drop_column('favorites', 'place_id')
    op.add_column('posts', sa.Column('sauna_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'saunas', ['sauna_id'], ['id'])
    op.drop_column('posts', 'place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('place_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'sauna_id')
    op.add_column('favorites', sa.Column('place_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'sauna_id')
    op.drop_table('saunas')
    # ### end Alembic commands ###
